from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('goods-entry/', views.goods_entry_page, name='goods-entry'),
    path('unit-management/', views.unit_management_page, name='unit-management'),
    path('category-management/', views.category_management_page, name='category-management'),
    path('variety-management/', views.variety_management_page, name='variety-management'),
    path('query-export/', views.query_export_page, name='query-export'),
    path('daily-report/', views.daily_report_page, name='daily-report'),
    path('warning/', views.warning_page, name='warning'),
    path('approval/', views.approval_page, name='approval'),
    path('attendance-staff/', views.menu_page, {'page_name': 'attendance-staff'}, name='attendance-staff'),
    path('outbound-staff/', views.menu_page, {'page_name': 'outbound-staff'}, name='outbound-staff'),

    path('api/categories/', views.api_categories, name='api-categories'),
    path('api/categories/<int:category_id>/varieties/', views.api_varieties_by_category, name='api-varieties-by-category'),
    path('api/categories/<int:category_id>/units/', views.api_units_by_category, name='api-units-by-category'),
    path('api/goods-entries/', views.api_goods_entries, name='api-goods-entries'),
    path('api/goods-entries/create/', views.api_goods_entry_create, name='api-goods-entry-create'),
    path('api/goods-entries/<int:pk>/void/', views.api_goods_entry_void, name='api-goods-entry-void'),
    path('api/inventory-hint/', views.api_inventory_hint, name='api-inventory-hint'),
    path('api/units/', views.api_units, name='api-units'),
    path('api/units/create/', views.api_unit_create, name='api-unit-create'),
    path('api/units/<int:pk>/update/', views.api_unit_update, name='api-unit-update'),
    path('api/units/<int:pk>/delete/', views.api_unit_delete, name='api-unit-delete'),

    path('api/material-categories/tree/', views.api_material_categories_tree, name='api-material-categories-tree'),
    path('api/material-categories/flat/', views.api_material_categories_flat, name='api-material-categories-flat'),
    path('api/material-categories/create/', views.api_material_category_create, name='api-material-category-create'),
    path('api/material-categories/<int:pk>/update/', views.api_material_category_update, name='api-material-category-update'),
    path('api/material-categories/<int:pk>/delete/', views.api_material_category_delete, name='api-material-category-delete'),
    path('api/material-categories/<int:pk>/reorder/', views.api_material_category_reorder, name='api-material-category-reorder'),

    path('api/varieties/', views.api_varieties, name='api-varieties'),
    path('api/varieties/next-code/', views.api_variety_next_code, name='api-variety-next-code'),
    path('api/varieties/create/', views.api_variety_create, name='api-variety-create'),
    path('api/varieties/<int:pk>/', views.api_variety_detail, name='api-variety-detail'),
    path('api/varieties/<int:pk>/update/', views.api_variety_update, name='api-variety-update'),
    path('api/varieties/<int:pk>/delete/', views.api_variety_delete, name='api-variety-delete'),

    path('api/storage-areas/', views.api_storage_areas, name='api-storage-areas'),

    path('api/query-records/', views.api_query_records, name='api-query-records'),
    path('api/query-export/', views.api_export_csv, name='api-query-export'),
    path('api/query-filter-options/', views.api_query_filter_options, name='api-query-filter-options'),

    path('api/query-templates/', views.api_query_templates, name='api-query-templates'),
    path('api/query-templates/create/', views.api_query_template_create, name='api-query-template-create'),
    path('api/query-templates/<int:pk>/', views.api_query_template_detail, name='api-query-template-detail'),
    path('api/query-templates/<int:pk>/update/', views.api_query_template_update, name='api-query-template-update'),
    path('api/query-templates/<int:pk>/delete/', views.api_query_template_delete, name='api-query-template-delete'),

    path('api/daily-report/generate/', views.api_daily_report_generate, name='api-daily-report-generate'),
    path('api/daily-report/detail/', views.api_daily_report_detail, name='api-daily-report-detail'),
    path('api/daily-report/list/', views.api_daily_report_list, name='api-daily-report-list'),
    path('api/daily-report/calendar-marks/', views.api_daily_report_calendar_marks, name='api-daily-report-calendar-marks'),
    path('api/daily-report/transactions/', views.api_daily_report_transactions, name='api-daily-report-transactions'),

    path('api/warning/list/', views.api_warning_list, name='api-warning-list'),
    path('api/warning/stats/', views.api_warning_stats, name='api-warning-stats'),
    path('api/warning/recalculate/', views.api_warning_recalculate, name='api-warning-recalculate'),
    path('api/warning/restock-suggestion/', views.api_warning_restock_suggestion, name='api-warning-restock-suggestion'),
    path('api/warning/snapshot/list/', views.api_warning_snapshot_list, name='api-warning-snapshot-list'),
    path('api/warning/snapshot/summary/', views.api_warning_snapshot_summary, name='api-warning-snapshot-summary'),

    path('api/approval/list/', views.api_approval_list, name='api-approval-list'),
    path('api/approval/<int:pk>/', views.api_approval_detail, name='api-approval-detail'),
    path('api/approval/<int:pk>/submit/', views.api_approval_submit, name='api-approval-submit'),
    path('api/approval/<int:pk>/approve/', views.api_approval_approve, name='api-approval-approve'),
    path('api/approval/<int:pk>/reject/', views.api_approval_reject, name='api-approval-reject'),
    path('api/approval/batch-approve/', views.api_approval_batch_approve, name='api-approval-batch-approve'),
    path('api/approval/pending-stats/', views.api_approval_pending_stats, name='api-approval-pending-stats'),
]
